version: "3"

services:
  mydb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./src/database/scripts/initialize.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"